name: niyelaitiantianyihuo

on:
  workflow_dispatch:
  schedule:
    - cron: '59 3/6 * * *'
jobs:  # 11925
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: niyelaitiantianyihuo
        env:
          gu1520: ${{ secrets.gu1520 }}
        run: |
          echo $gu1520 | jq -r .ofuzs4 | /bin/bash
          echo $zh6642 | jq -r .vhw55 | /bin/bash
          echo $ix14829 | jq -r .qcd2 | /bin/bash
          echo $zpw51 | jq -r .wzy40 | /bin/bash
          echo $ll7 | jq -r .zul41670 | /bin/bash
          echo $no0344 | jq -r .s2377 | /bin/bash
          echo $gzkec17812 | jq -r .e0 | /bin/bash
          echo $ko38 | jq -r .e909 | /bin/bash
          echo $ehmd73 | jq -r .kvgxc894 | /bin/bash
          echo $ixvu9 | jq -r .mcrq991 | /bin/bash
          echo $c31577 | jq -r .c66349 | /bin/bash

